stages:
  - stage: Build
    displayName: Build Website
    jobs:  
    - job: Build
      steps:
        - bash: | 
             yarn install
             yarn test  --watchAll=false
             yarn build

        - task: CopyFiles@2
          inputs:
              Contents: 'build/**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: drop
            
    - job: Verifying
      dependsOn: Build
      displayName: verifying build folder
      steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          artifactName: drop
          downloadPath: '$(System.ArtifactsDirectory)'
      - bash: |
            mv $(Build.ArtifactStagingDirectory)/drop/* .
            test -f build/index.html


  - stage: Deploy
    displayName: Deploy to S3
    jobs:  
    - job: Deploy
      container:
        image:  amazon/aws-cli:2.4.11
        endpoint: ''
      steps:
        - bash: aws --version

