stages:
  - stage: Build
    displayName: Build Laptop
    jobs:  
    - job: Build
      steps:
        - bash: | 
              echo "Building a laptop"
              mkdir build
              echo "MainBoard" >> build/laptop.txt
              cat build/laptop.txt
              echo "Keyboard" >> build/laptop.txt
  - stage: Test
    displayName: Test Laptop
    jobs:
      - job: Test
        steps: 
          - bash: |
              test -f build/laptop.txt
  