stages:
  - stage: Build
    displayName: Build Laptop
    jobs:  
    - job: Build
      steps:
        - bash: | 
              echo "Building a laptop"
              mkdir build
              echo "MainBoard" >> build/laptop.txt
              cat build/laptop.txt
              echo "Keyboard" >> build/laptop.txt
              cat build/laptop.txt
    - job: Test
      dependsOn: ['Build']
      steps: 
        - bash: test -f build/laptop.txt
      
  