stages:
  - stage: Build
    displayName: Build Website
    jobs:  
    - job: Build
      steps:
        - bash: | 
             yarn install
             yarn build

        - task: CopyFiles@2
          inputs:
              Contents: 'build/**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: .
    - job: Verifying
      dependsOn: Build
      displayName: verifying build folder
      steps:
        - download: current
        - bash: |
            echo "$(Build.ArtifactStagingDirectory)"
            ls $(Build.ArtifactStagingDirectory)/drop
            test -f /build/index.html

    - job: Test
      dependsOn: Verifying
      displayName: Running Test
      steps:
        - bash: yarn test
