stages:
  - stage: Build
    displayName: Build Website
    jobs:  
    - job: Build
      steps:
        - bash: | 
             yarn install
             yarn build
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: $(Build.StagingDirectory) 
            ArtifactName: drop
    - job: Verifying
      dependsOn: Build
      displayName: verifying build folder
      steps:
        - download: current
          artifact: drop
        - bash: |
            ls
            $(Build.StagingDirectory)
            test -f /build/index.html

    - job: Test
      dependsOn: Verifying
      displayName: Running Test
      steps:
        - bash: yarn test
