stages:
  - stage: Build
    displayName: Build Laptop
    jobs:  
    - job: Build
      steps:
        - bash: | 
              echo "Building a laptop"
              mkdir build
              echo "MainBoard" >> build/laptop.txt
              cat build/laptop.txt
              echo "Keyboard" >> build/laptop.txt
              cat build/laptop.txt
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)' # string. Required. Path to publish. Default: $(Build.ArtifactStagingDirectory).
            ArtifactName: 'drop' # string. Required. Artifact name. Default: drop.
            publishLocation: 'Container'
  - stage: Test
    dependsOn: Build
    displayName: Test Laptop
    jobs:
      - job: Test
        steps: 
        - download: current
          artifact: drop
        - bash: | 
            cat build/laptop.txt
  