stages:
  - stage: Build
    displayName: Build Laptop
    jobs:  
    - job: Build
      steps:
        - bash: | 
              echo "Building a laptop"
              mkdir build
              echo "MainBoard" >> build/laptop.txt
              cat build/laptop.txt
              echo "Keyboard" >> build/laptop.txt
              cat build/laptop.txt
        - publish: '$(Build.ArtifactStagingDirectory)/scripts'
          displayName: 'Publish powershell scripts for later use'
          artifact: dropScripts
  - stage: Test
    dependsOn: Build
    displayName: Test Laptop
    jobs:
      - job: Test
        steps: 
        - download: current
          artifact: dropScripts
        - script: test -f build/laptop.txt
  